language: node_js
sudo: false
addons:
    code_climate:
        repo_token: 5454ddcc127e2576769824c6702cae24336ebc3419d20850464aa03ed697ccee
install:
  - "npm install npm -g"
  - "npm install"
script:
  - "npm run travis"
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
cache:
  directories:
    - 'node_modules'
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
